springdoc:
  swagger-ui:
    path: /swagger-ui.hml
    enabled: false

server:
  port: 48152

custom:
  activeprofilename: prod
    
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true